apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aiops-prometheus
  namespace: default
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      app: aiops
